import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Suspense } from 'react';

import { categories } from '@/app/api/categories/constants';
import { ResponseList } from '@/features/_api/api.types';
import { Category } from '@/features/categories/api/categories.types';
import { Footer } from '@/features/home/components/footer';
import { Header } from '@/features/home/components/header';
import StoreRouteChangeSender from '@/features/store/components/store-route-change-sender';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

// @see https://nextjs-faq.com/fetch-api-in-rsc
const mockCategories = {
  data: categories,
  meta: {},
} satisfies ResponseList<Category>;

const RootLayout = async (props: Props) => {
  const { children } = props;
  const featuredCategories = mockCategories;
  return (
    <>
      <ThemeProvider attribute="class" defaultTheme="light">
        <div className="flex min-h-screen flex-col bg-[#f8f7f3]">
          <Header categories={featuredCategories.data} />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </ThemeProvider>

      <Suspense>
        <StoreRouteChangeSender />
      </Suspense>
    </>
  );
};

export default RootLayout;
