import { ProductDetails } from '@/features/product-details/api/product-details.types';
import { Product } from '@/features/products/api/products.type';

export const products: Product[] = [
  {
    id: '1',
    title: 'Organic Carrots',
    price: 2.99,
    salePrice: 2.49,
    image: '/images/products/carrots.png',
    images: ['/images/products/carrots.png'],
    type: 'Organic',
    farm: 'Green Valley Farms',
    category: 'Vegetables',
    description: 'Fresh, sweet, and crunchy organic carrots.',
    unit: 'bunch',
    inStock: true,
    featured: true,
  },
  {
    id: '2',
    title: 'Free Range Eggs',
    price: 4.5,
    image: '/images/products/eggs.png',
    images: ['/images/products/eggs.png'],
    type: 'Local',
    farm: 'Sunny Hen Ranch',
    category: 'Dairy & Eggs',
    description: 'A dozen free-range brown eggs, packed with flavor.',
    unit: 'dozen',
    inStock: true,
  },
  {
    id: '3',
    title: 'Raw Honey',
    price: 9.99,
    image: '/images/products/honey.png',
    images: ['/images/products/honey.png'],
    type: 'Local',
    farm: 'Buzzin’ Bees Apiary',
    category: 'Pantry',
    description: 'Golden, unprocessed honey straight from the hive.',
    unit: 'jar',
    inStock: true,
    featured: true,
  },
  {
    id: '4',
    title: 'Fresh Milk',
    price: 3.5,
    image: '/images/products/milk.png',
    images: ['/images/products/milk.png'],
    type: 'Conventional',
    farm: 'Dairy Hill Farm',
    category: 'Dairy & Eggs',
    description: 'Whole milk from pasture-raised cows.',
    unit: 'liter',
    inStock: true,
  },
  {
    id: '5',
    title: 'Golden Potatoes',
    price: 1.99,
    image: '/images/products/potatoes.png',
    images: ['/images/products/potatoes.png'],
    type: 'Conventional',
    farm: 'Harvest Hill',
    category: 'Vegetables',
    description: 'Starchy and smooth-skinned golden potatoes.',
    unit: 'kg',
    inStock: true,
  },
  {
    id: '6',
    title: 'Organic Kale',
    price: 2.25,
    image: '/images/products/kale.png',
    images: ['/images/products/kale.png'],
    type: 'Organic',
    farm: 'Leaf & Root Farms',
    category: 'Vegetables',
    description: 'Dark green, nutrient-packed organic kale.',
    unit: 'bunch',
    inStock: false,
  },
  {
    id: '7',
    title: 'Heirloom Tomatoes',
    price: 4.75,
    image: '/images/products/tomatoes.png',
    images: ['/images/products/tomatoes.png'],
    type: 'Organic',
    farm: 'Old Vine Farms',
    category: 'Vegetables',
    description: 'Colorful, juicy tomatoes grown with care.',
    unit: 'kg',
    inStock: true,
  },
  {
    id: '8',
    title: 'Sweet Corn',
    price: 3.0,
    salePrice: 2.5,
    image: '/images/products/corn.png',
    images: ['/images/products/corn.png'],
    type: 'Local',
    farm: 'Golden Acres',
    category: 'Vegetables',
    description: 'Fresh-picked ears of sweet corn.',
    unit: 'pack',
    inStock: true,
  },
  {
    id: '9',
    title: 'Pasture-Raised Chicken',
    price: 14.99,
    image: '/images/products/chicken.png',
    images: ['/images/products/chicken.png'],
    type: 'Conventional',
    farm: 'Feather Ridge Farms',
    category: 'Meat & Poultry',
    description: 'Whole chicken raised with care on pasture.',
    unit: 'each',
    inStock: true,
  },
  {
    id: '10',
    title: 'Fresh Lettuce Mix',
    price: 2.99,
    image: '/images/products/lettuce.png',
    images: ['/images/products/lettuce.png'],
    type: 'Organic',
    farm: 'Morning Dew Greens',
    category: 'Vegetables',
    description: 'Crisp and colorful lettuce blend.',
    unit: 'bag',
    inStock: true,
  },
  {
    id: '11',
    title: 'Goat Cheese',
    price: 6.5,
    image: '/images/products/goat-cheese.png',
    images: ['/images/products/goat-cheese.png'],
    type: 'Local',
    farm: 'Willow Creek Dairy',
    category: 'Dairy & Eggs',
    description: 'Creamy goat cheese with tangy notes.',
    unit: 'wheel',
    inStock: true,
  },
  {
    id: '12',
    title: 'Apple Cider',
    price: 5.25,
    image: '/images/products/apple-cider.png',
    images: ['/images/products/apple-cider.png'],
    type: 'Local',
    farm: 'Orchard Lane',
    category: 'Beverages',
    description: 'Fresh-pressed apple cider with a fall kick.',
    unit: 'bottle',
    inStock: true,
  },
  {
    id: '13',
    title: 'Farm Fresh Apples',
    price: 3.49,
    image: '/images/products/apples.png',
    images: ['/images/products/apples.png'],
    type: 'Organic',
    farm: 'Apple Blossom Hill',
    category: 'Fruits',
    description: 'Crisp, juicy apples straight from the orchard.',
    unit: 'kg',
    inStock: true,
  },
  {
    id: '14',
    title: 'Zucchini',
    price: 1.8,
    image: '/images/products/zucchini.png',
    images: ['/images/products/zucchini.png'],
    type: 'Conventional',
    farm: 'Green Patch Farms',
    category: 'Vegetables',
    description: 'Tender and versatile green zucchini.',
    unit: 'kg',
    inStock: true,
  },
  {
    id: '15',
    title: 'Organic Strawberries',
    price: 5.99,
    image: '/images/products/strawberries.png',
    images: ['/images/products/strawberries.png'],
    type: 'Organic',
    farm: 'Berry Bliss',
    category: 'Fruits',
    description: 'Sweet and juicy organic strawberries.',
    unit: 'box',
    inStock: false,
  },
  {
    id: '16',
    title: 'Pumpkin',
    price: 4.25,
    image: '/images/products/pumpkin.png',
    images: ['/images/products/pumpkin.png'],
    type: 'Local',
    farm: 'Harvest Patch',
    category: 'Vegetables',
    description: 'Perfect for pies or fall decorations.',
    unit: 'each',
    inStock: true,
  },
  {
    id: '17',
    title: 'Fresh Peas',
    price: 3.25,
    image: '/images/products/peas.png',
    images: ['/images/products/peas.png'],
    type: 'Conventional',
    farm: 'Green Row Farms',
    category: 'Vegetables',
    description: 'Tender green peas hand-picked in season.',
    unit: 'bag',
    inStock: true,
  },
  {
    id: '18',
    title: 'Organic Beets',
    price: 2.75,
    image: '/images/products/beets.png',
    images: ['/images/products/beets.png'],
    type: 'Organic',
    farm: 'Root & Vine',
    category: 'Vegetables',
    description: 'Deep red organic beets full of flavor.',
    unit: 'bunch',
    inStock: true,
  },
  {
    id: '19',
    title: 'Fresh Basil',
    price: 1.99,
    image: '/images/products/basil.png',
    images: ['/images/products/basil.png'],
    type: 'Local',
    farm: 'Leaf & Vine',
    category: 'Herbs',
    description: 'Aromatic and flavorful fresh basil leaves.',
    unit: 'bunch',
    inStock: true,
  },
  {
    id: '20',
    title: 'Raw Almonds',
    price: 7.5,
    image: '/images/products/almonds.png',
    images: ['/images/products/almonds.png'],
    type: 'Conventional',
    farm: 'Nut Grove',
    category: 'Pantry',
    description: 'Unsalted, raw whole almonds.',
    unit: 'bag',
    inStock: true,
    featured: true,
  },
];

export const productDetails: ProductDetails[] = products.map((product) => ({
  ...product,
  discount: product.salePrice
    ? Math.round(((product.price - product.salePrice) / product.price) * 100)
    : 0,
  ingredients: [], // You might need to fetch or generate these based on the product
  nutritionalInfo: { calories: 0, protein: '', carbs: '', fat: '' }, // Placeholder, as this info isn't in the Product type
}));
