import { Product } from '@/features/products/api/products.type';

export const farmProducts: Product[] = [
  {
    id: '1',
    title: 'Organic Carrots',
    price: 2.99,
    salePrice: 2.49,
    image: '/images/products/carrot.jpg',
    images: ['/images/products/carrot.jpg'],
    type: 'Organic',
    farm: 'Green Valley Farms',
    category: 'Vegetables',
    description: 'Fresh, sweet, and crunchy organic carrots.',
    unit: 'bunch',
    inStock: true,
    featured: true,
  },
  {
    id: '2',
    title: 'Free Range Eggs',
    price: 4.5,
    image: '/images/products/eggs.jpg',
    images: ['/images/products/eggs.jpg'],
    type: 'Local',
    farm: 'Sunny Hen Ranch',
    category: 'Dairy & Eggs',
    description: 'A dozen free-range brown eggs, packed with flavor.',
    unit: 'dozen',
    inStock: true,
  },
  {
    id: '3',
    title: 'Raw Honey',
    price: 9.99,
    image: '/images/products/honey.jpg',
    images: ['/images/products/honey.jpg'],
    type: 'Local',
    farm: 'Buzzin’ Bees Apiary',
    category: 'Pantry',
    description: 'Golden, unprocessed honey straight from the hive.',
    unit: 'jar',
    inStock: true,
    featured: true,
  },
  {
    id: '4',
    title: 'Fresh Milk',
    price: 3.5,
    image: '/images/products/milk.jpg',
    images: ['/images/products/milk.jpg'],
    type: 'Conventional',
    farm: 'Dairy Hill Farm',
    category: 'Dairy & Eggs',
    description: 'Whole milk from pasture-raised cows.',
    unit: 'liter',
    inStock: true,
  },
  {
    id: '5',
    title: 'Golden Potatoes',
    price: 1.99,
    image: '/images/products/potatoes.jpg',
    images: ['/images/products/potatoes.jpg'],
    type: 'Conventional',
    farm: 'Harvest Hill',
    category: 'Vegetables',
    description: 'Starchy and smooth-skinned golden potatoes.',
    unit: 'kg',
    inStock: true,
  },
  {
    id: '6',
    title: 'Organic Kale',
    price: 2.25,
    image: '/images/products/kale.jpg',
    images: ['/images/products/kale.jpg'],
    type: 'Organic',
    farm: 'Leaf & Root Farms',
    category: 'Vegetables',
    description: 'Dark green, nutrient-packed organic kale.',
    unit: 'bunch',
    inStock: false,
  },
  {
    id: '7',
    title: 'Heirloom Tomatoes',
    price: 4.75,
    image: '/images/products/tomatoes.jpg',
    images: ['/images/products/tomatoes.jpg'],
    type: 'Organic',
    farm: 'Old Vine Farms',
    category: 'Vegetables',
    description: 'Colorful, juicy tomatoes grown with care.',
    unit: 'kg',
    inStock: true,
  },
  {
    id: '8',
    title: 'Sweet Corn',
    price: 3.0,
    salePrice: 2.5,
    image: '/images/products/corn.jpg',
    images: ['/images/products/corn.jpg'],
    type: 'Local',
    farm: 'Golden Acres',
    category: 'Vegetables',
    description: 'Fresh-picked ears of sweet corn.',
    unit: 'pack',
    inStock: true,
  },
  {
    id: '9',
    title: 'Pasture-Raised Chicken',
    price: 14.99,
    image: '/images/products/chicken.jpg',
    images: ['/images/products/chicken.jpg'],
    type: 'Conventional',
    farm: 'Feather Ridge Farms',
    category: 'Meat & Poultry',
    description: 'Whole chicken raised with care on pasture.',
    unit: 'each',
    inStock: true,
  },
  {
    id: '10',
    title: 'Fresh Lettuce Mix',
    price: 2.99,
    image: '/images/products/lettuce.jpg',
    images: ['/images/products/lettuce.jpg'],
    type: 'Organic',
    farm: 'Morning Dew Greens',
    category: 'Vegetables',
    description: 'Crisp and colorful lettuce blend.',
    unit: 'bag',
    inStock: true,
  },
  {
    id: '11',
    title: 'Goat Cheese',
    price: 6.5,
    image: '/images/products/goat-cheese.jpg',
    images: ['/images/products/goat-cheese.jpg'],
    type: 'Local',
    farm: 'Willow Creek Dairy',
    category: 'Dairy & Eggs',
    description: 'Creamy goat cheese with tangy notes.',
    unit: 'wheel',
    inStock: true,
  },
  {
    id: '12',
    title: 'Apple Cider',
    price: 5.25,
    image: '/images/products/apple-cider.jpg',
    images: ['/images/products/apple-cider.jpg'],
    type: 'Local',
    farm: 'Orchard Lane',
    category: 'Beverages',
    description: 'Fresh-pressed apple cider with a fall kick.',
    unit: 'bottle',
    inStock: true,
  },
  {
    id: '13',
    title: 'Farm Fresh Apples',
    price: 3.49,
    image: '/images/products/apples.jpg',
    images: ['/images/products/apples.jpg'],
    type: 'Organic',
    farm: 'Apple Blossom Hill',
    category: 'Fruits',
    description: 'Crisp, juicy apples straight from the orchard.',
    unit: 'kg',
    inStock: true,
  },
  {
    id: '14',
    title: 'Zucchini',
    price: 1.8,
    image: '/images/products/zucchini.jpg',
    images: ['/images/products/zucchini.jpg'],
    type: 'Conventional',
    farm: 'Green Patch Farms',
    category: 'Vegetables',
    description: 'Tender and versatile green zucchini.',
    unit: 'kg',
    inStock: true,
  },
  {
    id: '15',
    title: 'Organic Strawberries',
    price: 5.99,
    image: '/images/products/strawberries.jpg',
    images: ['/images/products/strawberries.jpg'],
    type: 'Organic',
    farm: 'Berry Bliss',
    category: 'Fruits',
    description: 'Sweet and juicy organic strawberries.',
    unit: 'box',
    inStock: false,
  },
  {
    id: '16',
    title: 'Pumpkin',
    price: 4.25,
    image: '/images/products/pumpkin.jpg',
    images: ['/images/products/pumpkin.jpg'],
    type: 'Local',
    farm: 'Harvest Patch',
    category: 'Vegetables',
    description: 'Perfect for pies or fall decorations.',
    unit: 'each',
    inStock: true,
  },
  {
    id: '17',
    title: 'Fresh Peas',
    price: 3.25,
    image: '/images/products/peas.jpg',
    images: ['/images/products/peas.jpg'],
    type: 'Conventional',
    farm: 'Green Row Farms',
    category: 'Vegetables',
    description: 'Tender green peas hand-picked in season.',
    unit: 'bag',
    inStock: true,
  },
  {
    id: '18',
    title: 'Organic Beets',
    price: 2.75,
    image: '/images/products/beets.jpg',
    images: ['/images/products/beets.jpg'],
    type: 'Organic',
    farm: 'Root & Vine',
    category: 'Vegetables',
    description: 'Deep red organic beets full of flavor.',
    unit: 'bunch',
    inStock: true,
  },
  {
    id: '19',
    title: 'Fresh Basil',
    price: 1.99,
    image: '/images/products/basil.jpg',
    images: ['/images/products/basil.jpg'],
    type: 'Local',
    farm: 'Leaf & Vine',
    category: 'Herbs',
    description: 'Aromatic and flavorful fresh basil leaves.',
    unit: 'bunch',
    inStock: true,
  },
  {
    id: '20',
    title: 'Raw Almonds',
    price: 7.5,
    image: '/images/products/almonds.jpg',
    images: ['/images/products/almonds.jpg'],
    type: 'Conventional',
    farm: 'Nut Grove',
    category: 'Pantry',
    description: 'Unsalted, raw whole almonds.',
    unit: 'bag',
    inStock: true,
    featured: true,
  },
];
