import { Metadata } from 'next';
import type { ReactNode } from 'react';

import { AdminSidebar } from '@/features/admin/components/admin-sidebar';
import QuickAccess from '@/features/admin/components/quick-access';
import { SidebarProvider, SidebarTrigger } from '@/features/base/components/ui/sidebar';

interface AdminLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App Admin',
  description: 'Generated by create next app',
};

export default function AdminLayout({ children }: AdminLayoutProps) {
  return (
    <div className="min-h-screen bg-gray-50">
      <SidebarProvider defaultOpen={true}>
        <div className="flex h-screen w-full overflow-hidden">
          <AdminSidebar />
          <div className="flex flex-1 flex-col overflow-hidden">
            <div className="flex items-center">
              <SidebarTrigger />
              <div className="flex-1 px-6">
                <QuickAccess />
              </div>
            </div>

            <main className="flex-1 overflow-auto p-6">{children}</main>
          </div>
        </div>
      </SidebarProvider>
    </div>
  );
}
